resolver: lts-17.6
pvp-bounds: upper

packages:
- .

extra-deps:
- language-javascript-0.7.0.0
- these-1.1.1.1
- github: purescript/purescript
  commit: v0.14.3
  subdirs:
    - lib/purescript-cst
    - '.'

nix:
  enable: false
  shell-file: stack.nix

flags:
  aeson-pretty:
    lib-only: true
